# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 三谖愺
subtitle: El Psy Congroo
email: alex4814.fu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  一切腐朽与神奇。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ruishengfu.me" # the base hostname & protocol for your site
twitter_username:   alex4814
douban_username:    alex4814
weibo_username:     alex4814
zhihu_username:     alex4814
github_username:    alex4814
facebook_username:  alex4814
linkedin_username:  alex4814

# Build settings
markdown: kramdown
